config:
  send_anonymous_usage_stats: False
  use_colors: True

scentbird:
  target: "postgres"
  outputs:
    postgres:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: postgres
      schema: public_aprokopev